services:
  mysql:
    image: mysql:8.1
    container_name: mysql-seventh
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seventh
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - seventh-network

volumes:
  mysql-data:

networks:
  seventh-network:
    driver: bridge
